# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d5a9edfe0e2d6ba83a88423169f57a5744cc7144918b6099d13c2c6889a67bdb13e2e72ee21f9e2387999a4f9424394379e4a14f7d968074da7619aad49cd8c

test:
  secret_key_base: 92e3a4e734225959fa09fff977e3d66fa7ae3125d5f8d8054da127814f40cf8e345eb40c080c2e4493f8b14afce0c3cc0b7813783bef71d9df532b19f691a249

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
